apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-serv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-serv
  template:
    metadata:
      labels:
        app: nginx-serv
    spec:
      containers:
        - name: nginx-serv
          image: nginx
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 20
